<a href="https://colab.research.google.com/github/HadyOmar21/Machine_Learning-Projects/blob/main/Project1_Rock_vs_Mine_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing The Libraries

In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection and Data Processing

In [24]:
#Load Data
sonar_data = pd.read_csv('Copy of sonar data.csv',header = None)

In [25]:
sonar_data.shape

(208, 61)

In [26]:
sonar_data.describe()

               0           1           2   ...          57          58          59
count  208.000000  208.000000  208.000000  ...  208.000000  208.000000  208.000000
mean     0.029164    0.038437    0.043832  ...    0.007949    0.007941    0.006507
std      0.022991    0.032960    0.038428  ...    0.006470    0.006181    0.005031
min      0.001500    0.000600    0.001500  ...    0.000300    0.000100    0.000600
25%      0.013350    0.016450    0.018950  ...    0.003600    0.003675    0.003100
50%      0.022800    0.030800    0.034300  ...    0.005800    0.006400    0.005300
75%      0.035550    0.047950    0.057950  ...    0.010350    0.010325    0.008525
max      0.137100    0.233900    0.305900  ...    0.044000    0.036400    0.043900

[8 rows x 60 columns]

In [34]:
sonar_data[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [27]:
#Seperating data and labels
X = sonar_data.drop(columns = 60,axis = 1)
Y = sonar_data[60]

Traning and test set split

In [28]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.1,stratify = Y,random_state = 1)

Model Training - Logistics Regression

In [29]:
model = LogisticRegression()

In [30]:
# Training the logistics Regression model with training data
model.fit(x_train,y_train)

LogisticRegression()

Model Evaluation

In [32]:
# accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

print(training_data_accuracy*100)

83.42245989304813

In [33]:
# accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction,y_test)

print(test_data_accuracy*100)

76.19047619047619

Predictive System

In [ ]:
input_data = ()

# changing input data to numpy array
input_data_numpy_array = np.asarray(input_data)

#reshape the data
input_data_reshaped = input_data_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)

if prediction[0] == 'R' :
  print("the object is a rock")
else :
  print("the object is a mine")